# Generated by Django 6.0.4 on 2026-04-25 12:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payouts', '0004_idempotencykey'),
    ]

    operations = [
        migrations.AddField(
            model_name='ledgerentry',
            name='payout',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='payouts.payout'),
        ),
    ]
