# Generated by Django 6.0.4 on 2026-04-25 15:56

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payouts', '0006_payout_last_attempt_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='idempotencykey',
            name='is_processing',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='idempotencykey',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, db_index=True),
        ),
        migrations.AlterField(
            model_name='idempotencykey',
            name='key',
            field=models.UUIDField(db_index=True),
        ),
        migrations.AlterField(
            model_name='ledgerentry',
            name='amount_paise',
            field=models.BigIntegerField(validators=[django.core.validators.MinValueValidator(1)]),
        ),
        migrations.AlterField(
            model_name='ledgerentry',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, db_index=True),
        ),
        migrations.AlterField(
            model_name='ledgerentry',
            name='entry_type',
            field=models.CharField(choices=[('credit', 'Credit'), ('hold', 'Hold'), ('debit', 'Debit')], max_length=10),
        ),
        migrations.AlterField(
            model_name='ledgerentry',
            name='payout',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ledger_entries', to='payouts.payout'),
        ),
        migrations.AlterField(
            model_name='payout',
            name='amount_paise',
            field=models.BigIntegerField(validators=[django.core.validators.MinValueValidator(1)]),
        ),
        migrations.AlterField(
            model_name='payout',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, db_index=True),
        ),
    ]
